---
- name: Ensure node_exporter user exists
  user:
    name: node_exporter
    shell: /usr/sbin/nologin
    create_home: no

- name: Download Node Exporter
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz"
    dest: /tmp/node_exporter.tar.gz

- name: Extract Node Exporter
  unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /tmp
    remote_src: true

- name: Copy Node Exporter binary
  copy:
    src: "/tmp/node_exporter-1.7.0.linux-amd64/node_exporter"
    dest: /usr/local/bin/node_exporter
    remote_src: yes
    mode: 0755
  notify: restart node_exporter

- name: Install systemd service
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
  notify: restart node_exporter

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Enable & start node_exporter
  systemd:
    name: node_exporter
    enabled: yes
    state: started
